version: '3.8'

services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - go_network

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    networks:
      - go_network

networks:
  go_network:
    driver: bridge
